site_name: Mind2Web
site_description: Towards a Generalist Agent for the Web
site_author: Xiang Deng, Yu Gu, Boyuan Zheng, Shijie Chen, Samuel Stevens, Boshi Wang, Huan Sun, Yu Su
site_url: https://your-website-url.com
repo_url: https://github.com/OSU-NLP-Group/Mind2Web
repo_name: GitHub
site_favicon: static/images/favicon.svg

theme:
  name: material
  custom_dir: theme
  language: en
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: static/images/favicon.svg
  logo: static/images/logo.svg
  features:
    - navigation.expand
    - navigation.section
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  icons:
    font: material

extra_css:
  - static/css/bulma.min.css
  - static/css/bulma-carousel.min.css
  - static/css/bulma-slider.min.css
  - static/css/fontawesome.all.min.css
  - https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css
  - static/css/index.css

extra_javascript:
  - https://cdn.plot.ly/plotly-latest.min.js
  - https://d3js.org/d3.v4.js
  - https://d3js.org/d3-scale-chromatic.v1.min.js
  - https://cdn.jsdelivr.net/npm/d3plus-text@1
  - https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - static/js/fontawesome.all.min.js
  - static/js/bulma-carousel.min.js
  - static/js/bulma-slider.min.js
  - https://www.googletagmanager.com/gtag/js?id=G-MZNP3SCQ1V

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md

plugins:
  - search

extra:
  analytics:
    provider: ga
    tracking_id: 'G-MZNP3SCQ1V'

google_analytics:
  - 'G-MZNP3SCQ1V'
